name       : perl-file-remove
version    : '1.58'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/File-Remove-1.58.tar.gz : 81f6ec83acab8ba042afe904334a26eb3a56c217bdb9981d237a89ab072fd0d8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Remove - Remove files and directories
description: |
    File::Remove - Remove files and directories
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
