name       : perl-file-remove
version    : 1.57
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/File-Remove-1.57.tar.gz : b3becd60165c38786d18285f770b8b06ebffe91797d8c00cc4730614382501ad
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Remove - Remove files and directories
description: |
    File::Remove - Remove files and directories
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
