name       : perl-file-remove
version    : '1.61'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/File-Remove-1.61.tar.gz : fd857f585908fc503461b9e48b3c8594e6535766bc14beb17c90ba58d5dc4975
homepage   : https://metacpan.org/pod/File::Remove
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Remove - Remove files and directories
description: |
    File::Remove::remove removes files and directories. It acts like /bin/rm, for the most part. Although unlink can be given a list of files, it will not remove directories; this module remedies that. It also accepts wildcards, * and ?, as arguments for filenames.
    File::Remove::trash accepts the same arguments as remove, with the addition of an optional, infrequently used "other platforms" hashref.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
